name: Wake Render App

on:
  schedule:
    - cron: '50 15 * * *'  # JST 0:50 = UTC 15:50
  workflow_dispatch:  # 手動実行も可

jobs:
  ping_render:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render healthcheck URL
        run: curl -s https://kousu-app.onrender.com/healthcheck
